import Head from 'next/head'
import Navbar from '../components/NavbarHome'
import {AiOutlinePhone} from 'react-icons/ai'
import {BiLockAlt, BiDownload} from 'react-icons/bi'
import Image from "next/image"
// import Footer from '../components/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,300;0,400;0,600;0,700;1,900&display=swap" rel="stylesheet"></link>
      </Head>
        <Navbar />
        <div className='d-flex position-relative bg-pallet-1'>
          <div className='container'>
            <div className='header d-flex justify-content-center align-items-center'>
              <div>
                <div className='mb-4'>
                  <div className='fs-0 fw-bolder text-white text-center'>Awesome App </div>
                  <div className='fs-0 fw-bolder text-white text-center'>For Saving Time.</div>
                </div>
                <div className='fs-5 text-white text-center mb-4'>
                    <div className='mb-2'>We bring you a mobile app for banking problems that</div>
                    <div>oftenly wasting much of your times.</div>
                </div>
                <div className='text-center mb-5'>
                  <button className='bg-white text-pallet-1 fw-bold fs-5 py-2 px-4 rounded border-0'>Try It Free</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <main className='mb-5 bg-pallet-5'>
          <div className='container'>
            <div className='d-flex align-items-center justify-content-center py-5 mb-5'>
              <div>
                <div className='fs-0 fw-bolder text-pallet-3 mb-4'>
                  <span className='text-pallet-1'>Why</span> Choose ZWallet
                </div>
                <div className='text-pallet-3 fs-5 text-center'>
                  <div className='mb-1'>We have some great features from the application and it’s totally free </div>
                  <div>to use by all users around the world.</div>
                </div>
              </div>
            </div>
            <div className='row mb-5'>
              <div className='col pt-3 pb-5'>
                <div className='text-center'>
                  <div className='d-flex justify-content-center my-4'>
                    <div className='rounded-circle icon bg-pallet-4 d-flex justify-content-center align-items-center'>
                        <AiOutlinePhone className='icon-phone text-pallet-1'/>
                      </div>
                  </div>
                  <div className='fw-bold fs-3 my-4'>24/7 Support</div>
                  <div className='px-5'>We have 24/7 contact support so you can contact us whenever you want and we will respond it.</div>
                </div>
              </div>
              <div className='col bg-pallet-2 shadow-dark rounded pt-3 pb-5'>
                <div className='text-center'>
                  <div className='d-flex justify-content-center my-4'>
                    <div className='rounded-circle icon bg-pallet-4 d-flex justify-content-center align-items-center'>
                        <BiLockAlt className='icon-phone text-pallet-1'/>
                      </div>
                  </div>
                  <div className='fw-bold fs-3 my-4'>Data Privacy</div>
                  <div className='px-5'>We make sure your data is safe in our database and we will encrypt any data you submitted to us.</div>
                </div>
              </div>
              <div className='col pt-3 pb-5'>
                <div className='text-center'>
                  <div className='d-flex justify-content-center my-4'>
                    <div className='rounded-circle icon bg-pallet-4 d-flex justify-content-center align-items-center'>
                        <BiDownload className='icon-phone text-pallet-1'/>
                      </div>
                  </div>
                  <div className='fw-bold fs-3 my-4'>Easy Download</div>
                  <div className='px-5'>Zwallet is 100% totally free to use it’s now available on Google Play Store and App Store.</div>
                </div>
              </div>
            </div>
          </div>
          <div className='bg-pallet-4'>
            <div className='container'>
              <div className='row py-5'>
                  <div className='col'>
                    <Image src='/images/microsoft.png' alt="microsoft" width={174} height={120} className='img-fluid'/>
                  </div>
                  <div className='col'>
                    <Image src='/images/dropbox.png' alt="dropbox" width={174} height={120} className='img-fluid'/>
                  </div>
                  <div className='col'>
                    <Image src='/images/dell.png' alt="dell" width={174} height={120} className='img-fluid'/>
                  </div>
                  <div className='col'>
                    <Image src='/images/hm.png' alt="hm" width={174} height={120} className='img-fluid'/>
                  </div>
                  <div className='col'>
                    <Image src='/images/airbnb.png' alt="airbnb" width={174} height={120} className='img-fluid'/>
                  </div>
                </div>
            </div>
            
          </div>
        </main>

      {/* <Footer /> */}
    </div>
  )
}
