/* eslint-disable react/react-in-jsx-scope */
import Head from 'next/head'
import Navbar from '../components/NavbarHome'
import {AiOutlinePhone} from 'react-icons/ai'
import {BiLockAlt, BiDownload} from 'react-icons/bi'
import {FaArrowLeft, FaArrowRight} from 'react-icons/fa'
import Image from 'next/image'
import { Container ,Row,Col} from 'react-bootstrap'
import Footer from '../components/Footer'


export default function Index() {

	return (
		<div >
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<div className='d-flex position-relative bg-pallet-1 pattern'>
				<div className='container'>
					<div className='header d-flex justify-content-center align-items-center'>
						<div>
							<div className='mb-4'>
								<div className='fs-0 fw-bolder text-white text-center'>Awesome App </div>
								<div className='fs-0 fw-bolder text-white text-center'>For Saving Time.</div>
							</div>
							<div className='fs-5 text-white text-center mb-4'>
								<div className='mb-2'>We bring you a mobile app for banking problems that</div>
								<div>oftenly wasting much of your times.</div>
							</div>
							<div className='text-center mb-5'>
								<button className='bg-white text-pallet-1 fw-bold fs-5 py-2 px-4 rounded border-0'>Try It Free</button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<main className='mb-5 bg-pallet-5'>
				<div className='container'>
					<div className='d-flex align-items-center justify-content-center py-5 mb-5'>
						<div>
							<div className='fs-0 fw-bolder text-pallet-3 mb-4'>
								<span className='text-pallet-1'>Why</span> Choose ZWallet
							</div>
							<div className='text-pallet-3 fs-5 text-center'>
								<div className='mb-1'>We have some great features from the application and it’s totally free </div>
								<div>to use by all users around the world.</div>
							</div>
						</div>
					</div>
					<div className='row mb-5'>
						<div className='col pt-3 pb-5'>
							<div className='text-center'>
								<div className='d-flex justify-content-center my-4'>
									<div className='rounded-circle icon bg-pallet-4 d-flex justify-content-center align-items-center'>
										<AiOutlinePhone className='icon-phone text-pallet-1'/>
									</div>
								</div>
								<div className='fw-bold fs-3 my-4'>24/7 Support</div>
								<div className='px-5'>We have 24/7 contact support so you can contact us whenever you want and we will respond it.</div>
							</div>
						</div>
						<div className='col bg-pallet-2 shadow-dark rounded pt-3 pb-5'>
							<div className='text-center'>
								<div className='d-flex justify-content-center my-4'>
									<div className='rounded-circle icon bg-pallet-4 d-flex justify-content-center align-items-center'>
										<BiLockAlt className='icon-phone text-pallet-1'/>
									</div>
								</div>
								<div className='fw-bold fs-3 my-4'>Data Privacy</div>
								<div className='px-5'>We make sure your data is safe in our database and we will encrypt any data you submitted to us.</div>
							</div>
						</div>
						<div className='col pt-3 pb-5'>
							<div className='text-center'>
								<div className='d-flex justify-content-center my-4'>
									<div className='rounded-circle icon bg-pallet-4 d-flex justify-content-center align-items-center'>
										<BiDownload className='icon-phone text-pallet-1'/>
									</div>
								</div>
								<div className='fw-bold fs-3 my-4'>Easy Download</div>
								<div className='px-5'>Zwallet is 100% totally free to use it’s now available on Google Play Store and App Store.</div>
							</div>
						</div>
					</div>
				</div>
				<div className='bg-pallet-4'>
					<div className='container'>
						<div className='row py-5'>
							<div className='col'>
								<Image src='/images/microsoft.png' alt="microsoft" width={174} height={120} className='img-fluid'/>
							</div>
							<div className='col'>
								<Image src='/images/dropbox.png' alt="dropbox" width={174} height={120} className='img-fluid'/>
							</div>
							<div className='col'>
								<Image src='/images/dell.png' alt="dell" width={174} height={120} className='img-fluid'/>
							</div>
							<div className='col'>
								<Image src='/images/hm.png' alt="hm" width={174} height={120} className='img-fluid'/>
							</div>
							<div className='col'>
								<Image src='/images/airbnb.png' alt="airbnb" width={174} height={120} className='img-fluid'/>
							</div>
						</div>
					</div>
            
				</div>
				<Container className='py-5'>
					<div className=''>
						<div>
							<div className='mb-3 d-flex justify-content-center'>
								<div className='fs-0 bg-pallet-4 fw-bolder rounded-pill text-center w-75 text-pallet-1'>
								Rp. 390.736.500
								</div>
							</div>
							<div className='mb-2'>
								<div className='fw-bold fs-0 text-pallet-3 text-center'><span className='text-pallet-1'>Money</span> has Been Transfered</div>
							</div>
							<div className='d-flex justify-content-center'>
								<div className='w-75 text-center fs-4'>That amount of money has been transfered from all users. We still counting and going strong!</div>
							</div>
							
						</div>
						
					</div>
					
				</Container>
				<div className='bg-pallet-4'>
					<div className='container'>
						<Row className='py-5'>
							<Col sm={4}>
								<Image src='/images/png-phone2.png' width={450} height={856} alt='app' />						
							</Col>
							<Col className='d-flex align-items-center' sm={8}>
								<div>
									<div>
										<div className='fs-a fw-bolder text-pallet-3'> All The <span className='text-pallet-1 '>Great</span> Zwallet Features. </div>
									</div>
									<div className='bg-white rounded-2 mb-3 py-4 px-4'>
										<div className='fs-5 text-pallet-3 fw-bold'><span className='text-pallet-1'>1.</span> Small Fee</div>
										<div>We only charge 5% of every success transaction done in Zwallet app.</div>
									</div>
									<div className='bg-white rounded-2 mb-3 py-4 px-4'>
										<div className='fs-5 text-pallet-3 fw-bold'><span className='text-pallet-1'>2.</span> Data secured</div>
										<div>All your data is secured properly in our system and it’s encrypted.</div>
									</div>
									<div className='bg-white rounded-2 mb-3 py-4 px-4'>
										<div className='fs-5 text-pallet-3 fw-bold'><span className='text-pallet-1'>3.</span> User Friendly</div>
										<div>Zwallet come up with modern and sleek design and not complicated.</div>
									</div>
								</div>
								
							</Col>
						</Row>
					</div>
				</div>
				<Container className='d-flex justify-content-center align-items center py-5'>
					<div>
						<div className='fs-a fw-bolder text-pallet-3 text-center mb-3 mt-5'>
							What Users are <span className='text-pallet-1'>Saying.</span>
						</div>
						<div className='d-flex justify-content-center mb-5'>
							<div className='text-center w-75 fs-5'>
								We have some great features from the application and it’s totally free to use by all users around the world.
							</div>
						</div>
						<div className='d-flex position-relative align-items-center'>
							<div className='bg-pallet-2 shadow-dark d-flex justify-content-center py-5 rounded-2'>
								<div className='text-center'>
									<div className='mb-3'>
										<Image src='/images/1.png' height={120} width={120} alt='testimoni'></Image>
									</div>
									<div className='mb-1'>
										<div className='fw-bold fs-4'>Hinata Shoyou</div>
									</div>
									<div className='mb-3'>
										<div className='text-center '>Volleyball Athlete</div>
									</div>
									<div className='py-3'>
										<div className='fs-5 px-5'>
									“This is the most outstanding app that I’ve ever try in my live, this app is such an amazing masterpiece and it’s suitable for you who is bussy with their bussiness and must transfer money to another person aut there. Just try this app and see the power!”
										</div>
									</div>
								</div>
							</div>
							<div className='position-absolute fs-2 bg-pallet-2 rounded py-1 px-2 shadow-dark ms-4'><FaArrowLeft /></div>
							<div className='position-absolute fs-2 bg-pallet-2 rounded py-1 px-2 shadow-dark end-0 me-4'><FaArrowRight /></div>
						</div>
					</div>
				</Container>
			</main>
			<Footer />
		</div>
	)
}
