import Head from 'next/head'
import Navbar from '../components/NavbarHome'
import {Container} from 'react-bootstrap'
// import Footer from '../components/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='d-flex position-relative bg-color1'>
        <Container >
          <Navbar />
          <div>Awesome App For Saving Time.</div>
        </Container>
      </div>
      
      <main >
        
      </main>

      {/* <Footer /> */}
    </div>
  )
}
